export const profileMessages = {
	title: 'My profile',
	lead: 'How you appear in the dashboard — and on the website’s About page, if an admin shows you there.',
	photoSection: 'Photo',
	photoHint: 'Your Google photo is used until you upload one.',
	detailsSection: 'Details',
	email: 'Email',
	role: 'Role',
	designation: 'Designation',
	designationHint: 'Set by an admin.',
	noDesignation: 'Not set',
	firstName: 'First name',
	lastName: 'Last name',
	linksSection: 'Links',
	linkedin: 'LinkedIn',
	x: 'X (Twitter)',
	portfolio: 'Portfolio or website',
	linkPlaceholder: 'https://',
	save: 'Save profile',
	saved: 'Profile saved.',
	photoSaved: 'Photo updated.',
	photoRemoved: 'Photo removed.',
	photoRemovedGoogle: 'Photo removed — your Google photo is back.'
} as const;
